name: Docker Jobs

on:
  workflow_dispatch:

env:
  TERM: dumb

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      run: |
        hostid

  job2:
    runs-on: ubuntu-latest
    steps:
      run: |
        hostid
